/*
 * TimerWindow.java

    EVE Online Ratting Advisor
    Copyright (C) 2016  Anibal Muñoz Calero

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package rattingadvisor;

import java.awt.Point;

/**
 *
 * @author Anibal
 */
public class TimerWindow extends javax.swing.JFrame {

    private boolean running = false;
    Shared shared = new Shared();
    int stopId = 0;
    
    /**
     * Creates new form TimerWindow
     */
    public TimerWindow(Point p) {
        
        initComponents();
        setResizable(false);
        setTitle("Countdown Timer");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocation(p);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hour = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minute = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        second = new javax.swing.JTextField();
        startStopCD = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(rattingadvisor.RattingAdvisor.class).getContext().getResourceMap(TimerWindow.class);
        hour.setText(resourceMap.getString("hour.text")); // NOI18N
        hour.setName("hour"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        minute.setText(resourceMap.getString("minute.text")); // NOI18N
        minute.setName("minute"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        second.setText(resourceMap.getString("second.text")); // NOI18N
        second.setName("second"); // NOI18N

        startStopCD.setText(resourceMap.getString("startStopCD.text")); // NOI18N
        startStopCD.setName("startStopCD"); // NOI18N
        startStopCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopCDActionPerformed(evt);
            }
        });

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        idTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idTextField.setText(resourceMap.getString("idTextField.text")); // NOI18N
        idTextField.setName("idTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hour, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minute, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(startStopCD))
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(minute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startStopCD)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startStopCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopCDActionPerformed
        
        int hour;
        int minute;
        int second;
        Thread timer;
        
        if(!running){
            
            try {
                hour = Integer.parseInt(this.hour.getText());
            } catch (Exception e) {
                hour = 0;
                this.hour.setText("00");
            }
            
            try {
                minute = Integer.parseInt(this.minute.getText());
            } catch (Exception e) {
                minute = 0;
                this.minute.setText("00");
            }
            
            try {
                second = Integer.parseInt(this.second.getText());
            } catch (Exception e) {
                second = 0;
                this.second.setText("00");
            }
            
            shared.getStopTimerMusic().add(false);
            stopId = shared.getStopTimerMusic().size()-1;
            
            timer = new TimerThread(hour, minute, second, idTextField.getText(), this.hour, this.minute, this.second, this, stopId);
            timer.start();
            
            this.hour.setEnabled(false);
            this.minute.setEnabled(false);
            this.second.setEnabled(false);
            this.startStopCD.setText("Close CD");
            
            running = true;
            
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            
        }else{
            
            shared.getStopTimerMusic().set(stopId, true);
            dispose();
            
        }
        
    }//GEN-LAST:event_startStopCDActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hour;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField minute;
    private javax.swing.JTextField second;
    private javax.swing.JButton startStopCD;
    // End of variables declaration//GEN-END:variables
}
